### ISSUE TITLE
Can't use the plugin: "The `labels` prop in component overrides has been removed."

### ISSUE THREAD

**Issue by felixmilazeck-agenturtriebwerk** [HiDeoo/starlight-versions#8]
### Describe the bug

When using the plugin, Astro crashes. 

```
[ERROR] [AstroUserError] The `labels` prop in component overrides has been removed.
  Hint:
    Replace `Astro.props.labels["search.label"]` with `Astro.locals.t("search.label")` instead.
    For more information see https://starlight.astro.build/guides/i18n/#using-ui-translations
```
Stracktrace: 

```
AstroUserError: The `labels` prop in component overrides has been removed.
    at Object.get (/home/fmilazeck/wsl_projects/_development/wordpress_docs/wordpress-docs/node_modules/@astrojs/starlight/utils/i18n.ts:16:10)
    at /home/fmilazeck/wsl_projects/_development/wordpress_docs/wordpress-docs/node_modules/starlight-versions/components/VersionSearch.astro:19:16
    at AstroComponentInstance.VersionSearch [as factory] (/home/fmilazeck/wsl_projects/_development/wordpress_docs/wordpress-docs/node_modules/astro/dist/runtime/server/astro-component.js:16:12)
    at AstroComponentInstance.init (/home/fmilazeck/wsl_projects/_development/wordpress_docs/wordpress-docs/node_modules/astro/dist/runtime/server/render/astro/instance.js:32:29)
    at AstroComponentInstance.render (/home/fmilazeck/wsl_projects/_development/wordpress_docs/wordpress-docs/node_modules/astro/dist/runtime/server/render/astro/instance.js:42:36)
    at Object.render (/home/fmilazeck/wsl_projects/_development/wordpress_docs/wordpress-docs/node_modules/astro/dist/runtime/server/render/component.js:366:22)
    at Module.renderChild (/home/fmilazeck/wsl_projects/_development/wordpress_docs/wordpress-docs/node_modules/astro/dist/runtime/server/render/any.js:31:17)
```

### To Reproduce

Add the plugin to your Astro config file.

### Expected behavior

Dev and build mode should not crash. The page should be displayed accordingly.

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
Thanks for the report 🙌 

The issue was due to a breaking change in Starlight [`0.28.0`](https://github.com/withastro/starlight/releases/tag/%40astrojs%2Fstarlight%400.28.0) recently released. The new [`0.3.0`](https://github.com/HiDeoo/starlight-versions/releases/tag/v0.3.0) version of the plugin that I've just released should fix the issue.
